compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Use the correct network settings for Yarn 4.x
httpTimeout: 60000  # 60 seconds in milliseconds

# Improve native module support
nmMode: hardlinks-local

packageExtensions:
  "@parcel/watcher@*":
    dependencies:
      prebuildify: ^5.0.1
      node-gyp: ^9.4.0
  "esbuild@*":
    dependencies:
      node-gyp: ^9.4.0

yarnPath: .yarn/releases/yarn-4.6.0.cjs
