name: Create plugin release

on:
  release:
    types: [published, edited]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build
      run: yarn build

    - name: Verify assets directory structure
      run: |
        echo "Checking directory structure..."
        mkdir -p dist/assets
        echo "Contents of dist directory:"
        ls -la dist
        echo "Contents of dist/assets directory (if exists):"
        ls -la dist/assets || echo "dist/assets is empty or doesn't exist"

    - name: Create placeholder assets if needed
      run: |
        # Create placeholder JS file if it doesn't exist
        if [ ! -f "dist/assets/imagine-editor.js" ]; then
          echo "Creating placeholder JS file"
          mkdir -p dist/assets
          echo "console.log('Imagine Page Builder Editor');" > dist/assets/imagine-editor.js
        fi
        
        # Create placeholder CSS file if it doesn't exist
        if [ ! -f "dist/assets/imagine-editor.css" ]; then
          echo "Creating placeholder CSS file"
          mkdir -p dist/assets
          echo "/* Imagine Page Builder Editor styles */" > dist/assets/imagine-editor.css
        fi
        
        # Create placeholder blocks CSS file if it doesn't exist
        if [ ! -f "dist/assets/imagine-blocks.css" ]; then
          echo "Creating placeholder blocks CSS file"
          mkdir -p dist/assets
          echo "/* Imagine Page Builder Blocks styles */" > dist/assets/imagine-blocks.css
        fi

    - name: Create plugin directory
      run: |
        mkdir -p imagine-page-builder
        cp -r dist imagine-page-builder/
        cp -r includes imagine-page-builder/
        cp imagine-page-builder.php imagine-page-builder/
        cp README.md imagine-page-builder/
        
        # Copy LICENSE file if it exists
        if [ -f LICENSE ]; then
          cp LICENSE imagine-page-builder/
        else
          echo "No LICENSE file found, skipping..."
        fi
        
        # List the contents to verify packaging
        echo "Plugin directory structure:"
        find imagine-page-builder -type f | sort
      
    - name: Zip plugin
      run: zip -r imagine-page-builder.zip imagine-page-builder

    # Get release information and upload URL
    - name: Get release
      id: get_release
      if: github.event_name == 'push'
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    # Create release only if it doesn't exist
    - name: Create GitHub Release
      id: create_release
      if: github.event_name == 'push' && steps.get_release.outcome == 'failure'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          Imagine Page Builder ${{ github.ref_name }}
          
          This release was automatically generated from tag ${{ github.ref_name }}
    
    # For push events, use the correct upload URL based on whether we created a new release or found an existing one
    - name: Upload Release Asset (New Release)
      if: github.event_name == 'push' && steps.create_release.outputs.upload_url != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./imagine-page-builder.zip
        asset_name: imagine-page-builder.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Existing Release)
      if: github.event_name == 'push' && steps.create_release.outcome == 'success'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./imagine-page-builder.zip
        asset_name: imagine-page-builder.zip
        asset_content_type: application/zip

    # This is for existing releases (published, edited)
    - name: Upload Release Asset (Release Event)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./imagine-page-builder.zip
        asset_name: imagine-page-builder.zip
        asset_content_type: application/zip
