name: Create plugin release

on:
  release:
    types: [published, edited]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build
      run: yarn build

    - name: Create plugin directory
      run: |
        mkdir -p imagine-page-builder
        cp -r dist imagine-page-builder/
        cp -r includes imagine-page-builder/
        cp imagine-page-builder.php imagine-page-builder/
        cp README.md imagine-page-builder/
        
        # Copy LICENSE file if it exists
        if [ -f LICENSE ]; then
          cp LICENSE imagine-page-builder/
        else
          echo "No LICENSE file found, skipping..."
        fi
      
    - name: Zip plugin
      run: zip -r imagine-page-builder.zip imagine-page-builder

    # This handles when a tag is pushed but no release exists yet
    - name: Auto-create release if tag pushed without release
      id: create_release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: imagine-page-builder.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # This handles when operating on an existing release
    - name: Attach to existing release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: imagine-page-builder.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
