name: Create plugin release

on:
  release:
    types: [published, edited]
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build
      run: yarn build
      
    - name: Ensure asset PHP file exists
      run: |
        mkdir -p dist
        if [ "${{ hashFiles('dist/imagine-editor.asset.php') }}" == "" ]; then
          echo "Creating dist/imagine-editor.asset.php file"
          echo '<?php' > dist/imagine-editor.asset.php
          echo 'return array(' >> dist/imagine-editor.asset.php
          echo "    'dependencies' => array(" >> dist/imagine-editor.asset.php
          echo "        'wp-element'," >> dist/imagine-editor.asset.php
          echo "        'wp-components'," >> dist/imagine-editor.asset.php
          echo "        'wp-blocks'," >> dist/imagine-editor.asset.php
          echo "        'wp-i18n'," >> dist/imagine-editor.asset.php
          echo "        'wp-api-fetch'," >> dist/imagine-editor.asset.php
          echo "        'wp-editor'" >> dist/imagine-editor.asset.php
          echo "    )," >> dist/imagine-editor.asset.php
          echo "    'version' => '1.0.0'" >> dist/imagine-editor.asset.php
          echo ");" >> dist/imagine-editor.asset.php
          echo "Created asset file successfully"
        else
          echo "dist/imagine-editor.asset.php already exists"
        fi

    - name: Create plugin directory
      run: |
        mkdir -p imagine-page-builder
        cp -r dist imagine-page-builder/
        cp -r includes imagine-page-builder/
        cp imagine-page-builder.php imagine-page-builder/
        cp README.md imagine-page-builder/
        
        # Copy LICENSE file if it exists
        if [ -f LICENSE ]; then
          cp LICENSE imagine-page-builder/
        else
          echo "No LICENSE file found, skipping..."
        fi
      
    - name: Zip plugin
      run: zip -r imagine-page-builder.zip imagine-page-builder

    # This handles when a tag is pushed but no release exists yet
    - name: Auto-create release if tag pushed without release
      id: create_release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: imagine-page-builder.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # This handles when operating on an existing release
    - name: Attach to existing release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: imagine-page-builder.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
